title: Gourmandignes

collections:
  producteurs:
    output: true
  beaute:
    output: true
  boissons: 
    output: true
  boulangerie:
    output: true
  cremerie:
    output: true
  epicerie:
    output: true
  legumes:
    output: true
  maison:
    output: true
  viandes:
    output: true  
  coordinateurs:
    output: true
  contrats:
    output: true
  produits:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: location

plugins:
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
