title: Gourmandignes
remote_theme: gourmandignes/maquillage-gourmandignes

collections:
  producteurs:
    output: true
  produits:
    output: true
  coordinateurs:
    output: true
  contrats:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: location

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
